[package]
name = "mmtest"
version = "0.1.0"
edition = "2024"

[dependencies]
datafusion = "46.0.0"
maxminddb = "0.25.0"
rand = "0.9.0"
rayon = "1.10.0"
tokio = { version = "1.44.1", features = ["rt-multi-thread"] }
